name: 'Dependency Check scan'
description: 'Runs dependency check on checked out code.'
runs:
    using: 'docker'
    image: 'docker://owasp/dependency-check:latest'
    args:
        - '--scan'
        - '{{ github.workspace }}'
        - '--format' 
        - ' "ALL"'
        - '--project'
        - '{{ github.repository }}'
        - '--out'
        - '/github/workspace/reports'