name: 'Dependency Check scan'
description: 'Runs dependency check on checked out code.'
inputs:
    Source-Location:
        required: false
        default: '/github/workspace'
    Project-Name:
        required: true
    Report-Location:
        required: false
        default: '/github/workspace/reports'
runs:
    using: 'docker'
    image: 'docker://owasp/dependency-check:latest'
    args:
        - '--scan'
        - '${{ inputs.Source-Location }}'
        - '--format' 
        - 'ALL'
        - '--project'
        - '${{ inputs.Project-Name }}'
        - '--out'
        - '${{ inputs.Report-Location }}'